name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: |
          cd MultipleRobloxInstances/MultipleRobloxInstances
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultipleRobloxInstances
          path: MultipleRobloxInstances/MultipleRobloxInstances/out/*.exe